Repository zertidana/LNHM, pull requests merged in 2025-06, with the labels that each got.

#21 19 create user stories
  documentation/user_stories.md
Labels: documentation

#22 2 create ci pipeline
  .github/workflows/ci.yml
Labels: enhancement

#36 Bug fixes
  .gitignore
  schema.sql
Labels: bug

#53 33 etl record historical data
  pipeline/extract.py
  pipeline/load.py
  pipeline/log.py
  pipeline/test_load.py
  pipeline/test_transform.py
  pipeline/transform.py
  pipeline/utilities.py
Labels: enhancement

#54 8 set up terraform infrastructure on aws
  .github/workflows/ci.yml
  terraform/main.tf
  terraform/notes.md
  terraform/variables.tf
Labels: enhancement

#68 40 add lambdaschedule to run etl every minute
  pipeline/README.md
  pipeline/etl_controller.py
  pipeline/lambda_handlers.py
  pipeline/load.py
  pipeline/test_load.py
  pipeline/test_transform.py
  pipeline/transform.py
Labels: enhancement

#71 61 schema store error data
  pipeline/extract.py
  pipeline/test_transform.py
  pipeline/transform.py
  schema.sql
Labels: enhancement

#74 9 creating pipeline dockerfile
  pipeline/Dockerfile
  pipeline/README.md
  pipeline/requirements.txt
  pipeline/test_lambda_handlers.py
  terraform/main.tf
Labels: enhancement

#80 HOTFIX: 79 bug error insertion
  pipeline/load.py
  schema.sql
Labels: bug

#91 76 create a lambda to archive and summarise 24hr data
  archiver/Dockerfile
  archiver/README.md
  archiver/archive_plant_reading.py
  archiver/requirements.txt
  archiver/utilities.py
  pipeline/requirements.txt
  pipeline/transform.py
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#95 94 Adding test coverage for archiver
  archiver/test_archive.py
  archiver/utilities.py
Labels: enhancement

#96 75 create lambda for ses
  alerter/Dockerfile
  alerter/README.md
  alerter/requirements.txt
  alerter/send_alerts.py
  alerter/utilities.py
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#97 87 Changed plant ids to plant names
  streamlit/Daily_Data.py
  streamlit/pages/Historical_Data.py
  streamlit/visualisations/visualisations.py
  streamlit/visualisations/visualisations_archived_data.py
Labels: enhancement, high priority

#101 98 fix ses email sending
  alerter/requirements.txt
  alerter/send_alerts.py
  pipeline/etl_controller.py
  pipeline/lambda_handlers.py
  pipeline/load.py
  pipeline/test_lambda_handlers.py
  terraform/main.tf
  terraform/variables.tf
Labels: bug
